import { userRole } from "@/utils/utils";
import {
	ContactRound,
	School,
	Component,
	BookMarked,
	Users2,
	Home,
	Columns3,
	LibraryBig,
	AlignEndHorizontal,
} from "lucide-react";

export const sideBarNavs = [
	{
		title: "Trang chủ",
		icon: Home,
		path: "/home",
		variant: "default",
		role: ["All"],
	},
	{
		title: "Tài khoản",
		icon: Users2,
		path: "/account",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Học sinh",
		icon: ContactRound,
		path: "/student",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Tổ bộ môn",
		icon: Component,
		path: "/department",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Giáo viên",
		icon: ContactRound,
		path: "/teacher",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Học kỳ",
		icon: BookMarked,
		path: "/semester",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Lớp học",
		icon: School,
		path: "/classroom",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Phân công giảng dạy",
		icon: Columns3,
		path: "/assignment",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Học tập",
		icon: LibraryBig,
		path: "/study",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Hạnh kiểm",
		icon: AlignEndHorizontal,
		path: "/conduct",
		variant: "ghost",
		role: [userRole.admin],
	},
	{
		title: "Hồ sơ giáo viên",
		icon: LibraryBig,
		path: "/teacher-info",
		variant: "ghost",
		role: [userRole.gv, userRole.gvcn],
	},
	{
		title: "Tổ bộ môn",
		icon: Component,
		path: "/teacher-group",
		variant: "ghost",
		role: [userRole.gv, userRole.gvcn],
	},
	{
		title: "Giáo viên chủ nhiệm",
		icon: ContactRound,
		path: "/teacher-home",
		variant: "ghost",
		role: [userRole.gvcn],
	},
	{
		title: "Lớp giảng dạy",
		icon: School,
		path: "/teacher-home",
		variant: "ghost",
		role: [userRole.gv, userRole.gvcn],
	},
];
